### ISSUE TITLE
accountBalance requires securityCredential and certPath

### ISSUE THREAD

**Issue by grinono** [safaricom/mpesa-node-library#14]
docs inform on a single requirement of providing consumerKey and consumerSecret.

Though for the accountBalance request securityCredential is also a requirement. Where to find this for our Mpesa account?

**Comment by grinono** [comment]
is that also the case for the myKey.cert?

**Comment by DGatere** [comment]
Yes at https://developer.safaricom.co.ke/docs#introduction

You have Sandbox Certificate and Production Certificate provided as links on the left pane

**Comment by grinono** [comment]
when I login and check api details for the app, i find consumerKey and consumerSecret. But where to find the "securityCredential"?
