### ISSUE TITLE
where to find: securityCredential

### ISSUE THREAD

**Issue by grinono** [safaricom/mpesa-node-library#15]
When I login and check api details for the app, I find consumerKey and consumerSecret. But your package/The REST also requires  the "securityCredential" . Where can we find this after going life is initiated?

**Comment by geofmureithi** [comment]
As I said in #14 Please check your developer portal for credentials.
If you feel you are missing something, please email apifeedback@safaricom.co.ke
<img width="1334" alt="screenshot 2018-11-26 at 15 26 24" src="https://user-images.githubusercontent.com/6939342/49014187-521cbd80-f190-11e8-8302-e23a36d2d9be.png">

**Comment by grinono** [comment]
sure found that interface, but that's just for a Testing sandbox, Changing that to Production is not possible. So where to find working Security credentials for a production env.?

**Comment by geofmureithi** [comment]
Please talk to apifeedback@safaricom.co.ke if you are having issues with going to prod. This is a tool and we cant offer support here.

**Comment by geofmureithi** [comment]
@grinono 
Additionally,
If you dont know how to go to production, please click "Go Live"  on daraja or use this:
https://developer.safaricom.co.ke/production_profile/form_production_profile
